server:
  port: 8002
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i8a803.p.ssafy.io:3002/mpti_trainer?serverTimezone=Asia/Seoul
    username: root
    password: ehdrms

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1

  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8002

logging.level:
  org.hibernate.SQL: debug